//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Burnbytes.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Burnbytes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string Button_Exit {
            get {
                return ResourceManager.GetString("Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clean selected items ähnelt.
        /// </summary>
        internal static string Button_RunCleaning {
            get {
                return ResourceManager.GetString("Button_RunCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About this clean-up ähnelt.
        /// </summary>
        internal static string Label_AboutCurrentCleanupHandler {
            get {
                return ResourceManager.GetString("Label_AboutCurrentCleanupHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculating... ähnelt.
        /// </summary>
        internal static string Label_Calculating {
            get {
                return ResourceManager.GetString("Label_Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Burnbytes is cleaning up unnecessary files on your machine. ähnelt.
        /// </summary>
        internal static string Label_Cleaner_Description {
            get {
                return ResourceManager.GetString("Label_Cleaner_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cleaning: ähnelt.
        /// </summary>
        internal static string Label_Cleaning {
            get {
                return ResourceManager.GetString("Label_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cleaning up drive  ähnelt.
        /// </summary>
        internal static string Label_Cleanup {
            get {
                return ResourceManager.GetString("Label_Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the drive you want to clean up. ähnelt.
        /// </summary>
        internal static string Label_DriveSelection_Description {
            get {
                return ResourceManager.GetString("Label_DriveSelection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drives ähnelt.
        /// </summary>
        internal static string Label_DriveSelection_Drives {
            get {
                return ResourceManager.GetString("Label_DriveSelection_Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files to delete: ähnelt.
        /// </summary>
        internal static string Label_FilesToDelete {
            get {
                return ResourceManager.GetString("Label_FilesToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you&apos;re low on space, we can try to clean up files using the settings on this page. ähnelt.
        /// </summary>
        internal static string Label_HandlerChoice_Information {
            get {
                return ResourceManager.GetString("Label_HandlerChoice_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can use Disk Cleanup to free up to {0} of disk space on {1}. ähnelt.
        /// </summary>
        internal static string Label_Introduction {
            get {
                return ResourceManager.GetString("Label_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More storage settings ähnelt.
        /// </summary>
        internal static string Label_MoreStorageSettings {
            get {
                return ResourceManager.GetString("Label_MoreStorageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} (Preparing...) ähnelt.
        /// </summary>
        internal static string Label_Preparing {
            get {
                return ResourceManager.GetString("Label_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Burnbytes is calculating how much space you will be able to free on {0}. This may take a few minutes to complete. ähnelt.
        /// </summary>
        internal static string Label_Scanner_Description {
            get {
                return ResourceManager.GetString("Label_Scanner_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning: ähnelt.
        /// </summary>
        internal static string Label_Scanning {
            get {
                return ResourceManager.GetString("Label_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View files ähnelt.
        /// </summary>
        internal static string Label_ShowFiles {
            get {
                return ResourceManager.GetString("Label_ShowFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storage ähnelt.
        /// </summary>
        internal static string Label_Storage {
            get {
                return ResourceManager.GetString("Label_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        internal static string Label_System {
            get {
                return ResourceManager.GetString("Label_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About {0} ähnelt.
        /// </summary>
        internal static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}
        ///Aimed as open community cleaner!
        ///Version {1}
        ///
        ///This is my vision of a Disk cleanup utility in Windows 10, which should have been implemented by Microsoft instead of Storage sense. It combines the classic menu navigation of Disk cleanup (cleanmgr.exe) with a modernized Windows 10 typical user interface.
        ///
        ///This project is based upon Albacore&apos;s Managed Disk Cleanup
        ///https://github.com/thebookisclosed/Comet)
        ///
        ///(C#) 2019, thebookisclosed
        ///https://twitter.com/thebookisclosed
        ///
        ///Modernised version
        ///(C#) 2 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Message_About {
            get {
                return ResourceManager.GetString("Message_About", resourceCulture);
            }
        }
    }
}
